import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import Header from "@/components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Goals",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex justify-start items-start h-screen overflow-hidden bg-[white]">
          <Navbar />
          <main className="w-full overflow-y-scroll h-screen">
            <Header />
            <div>{children}</div>
          </main>
        </main>
      </body>
    </html>
  );
}
