"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import Header from "@/components/Header/Header";
import Logout from "@/components/Modals/logout";
import { isLoggedIn } from "@/helper/helper";
import { useEffect, useState } from "react";
import Loader from "@/components/Modals/Loader";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Goals",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const [check, setCheck] = useState<boolean>(false);
  if (!isLoggedIn()) {
    return <Logout />;
  }

  useEffect(() => {
    const timeout = setTimeout(() => {
      setCheck(true);
    }, 5000);

    return () => clearTimeout(timeout);
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        {check ? (
          !isLoggedIn() ? (
            <Logout />
          ) : (
            <main className="flex justify-start items-start h-screen overflow-hidden bg-[white]">
              <Navbar />
              <main className="w-full overflow-y-scroll h-screen">
                <Header />
                <div>{children}</div>
              </main>
            </main>
          )
        ) : (
          <Loader />
        )}
      </body>
    </html>
  );
}
